
if ( NOT WIN32 )
	string( ASCII 27 Esc )
	set( ColorReset  "${Esc}[m" )
	set( ColorBold   "${Esc}[1m" )
	set( Red         "${Esc}[31m" )
	set( Green       "${Esc}[32m" )
	set( Yellow      "${Esc}[33m" )
	set( Blue        "${Esc}[34m" )
	set( Magenta     "${Esc}[35m" )
	set( Cyan        "${Esc}[36m" )
	set( White       "${Esc}[37m" )
	set( BoldRed     "${Esc}[1;31m" )
	set( BoldGreen   "${Esc}[1;32m" )
	set( BoldYellow  "${Esc}[1;33m" )
	set( BoldBlue    "${Esc}[1;34m" )
	set( BoldMagenta "${Esc}[1;35m" )
	set( BoldCyan    "${Esc}[1;36m" )
	set( BoldWhite   "${Esc}[1;37m" )
endif ( )

function ( q_message_colorize COLOR PARTS OUT )
	set ( VAL "${COLOR}[q] " )

	foreach ( PART ${PARTS} )
		if ( "${PART}" STREQUAL PATH )
			set( VAL "${VAL}${Cyan}" )
		else ( )
			set( VAL "${VAL}${PART}${COLOR}" )
		endif ( )
	endforeach ( )

	set( ${OUT} "${VAL}${ColorReset}" PARENT_SCOPE )
endfunction ( )

function ( q_message )
	q_message_colorize( "${Green}" "${ARGV}" msg )
	message( ${msg} )
endfunction ( )

function ( q_info )
	q_message_colorize( "${Yellow}" "${ARGV}" msg )
	message( ${msg} )
endfunction ( )

function ( q_warning )
	q_message_colorize( "${Magenta}" "${ARGV}" msg )
	message( ${msg} )
endfunction ( )

function ( q_error )
	q_message_colorize( "${Red}" "${ARGV}" msg )
	message( ${msg} )
endfunction ( )

function ( q_fatal )
	q_message_colorize( "${Red}" "${ARGV}" msg )
	message( FATAL_ERROR ${msg} )
endfunction ( )
